# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CacheTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CacheTest
pod 'YYCache'
pod 'FMDB'

end
