# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FunctionalReactivePixel' do

pod 'ReactiveCocoa' , ' 2.1.4'
pod 'libextobjc', '0.3'
pod 'SVProgressHUD', '0.9'

end
