# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'FunctionalReactivePixel' do

pod 'ReactiveCocoa' , ' 2.1.4'
pod 'libextobjc'
pod 'SVProgressHUD', '1.0'
pod 'ReactiveViewModel', tag: '0.1.2', git: 'https://github.com/ashfurrow/ReactiveViewModel.git'
pod 'AFImageDownloader'
pod '500px-iOS-api'

end
